### ISSUE TITLE
Kick instantly

### ISSUE THREAD

**Issue by awesomecoder3000** [theusaf/kahoot-session#9]
Hello, when I run the NPM module of Kahoot-Session, when entering the first question, the client disconnects, without any errors of traces. Any fixes? The NPM version was released 7 months ago, maybe this is fixed in a patch?

**Comment by theusaf** [comment]
The npm version is currently very outdated, I think it was using V1 of Kahoot, so it is no longer working. I am currently trying to fix this and update `kahoot-session`. See #7

**Comment by awesomecoder3000** [comment]
OK, thanks!
